# .github/workflows/deploy.yml
# ... (keep the top part of the file the same)

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Latest Rancher CLI and Configure Context
        run: |
          # Use the GitHub API to find the URL for the latest linux-amd64 CLI release
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/rancher/cli/releases/latest | \
          grep "browser_download_url.*linux-amd64" | cut -d '"' -f 4)

          # Download the file found above
          echo "Downloading Rancher CLI from $DOWNLOAD_URL"
          wget $DOWNLOAD_URL

          # The downloaded filename will change, so use a wildcard '*' to extract it
          tar -zxvf rancher-linux-amd64-*.tar.gz
          sudo mv rancher-*/rancher /usr/local/bin/

          # Login to your Rancher instance (this part is the same as before)
          rancher login ${{ secrets.RANCHER_URL }} --token ${{ secrets.RANCHER_TOKEN }} --insecure
          rancher context switch clk3s-nada

      - name: Update Kubernetes Manifest and Deploy
        run: |
          # This step remains the same
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/cm-to-inch-api:${{ github.sha }}|g' k8s/deployment.yaml
          rancher kubectl apply -f k8s/deployment.yaml